# Generated by Django 5.2.16 on 2026-07-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('tayyorlanmoqda', 'Tayyorlanmoqda'), ('yolda', "Yo'lda"), ('yetkazildi', 'Yetkazildi'), ('bekor_qilindi', 'Bekor qilindi')], default='yangi', max_length=20, verbose_name='Holat')),
                ('delivery_type', models.CharField(choices=[('yetkazib_berish', 'Yetkazib berish'), ('olib_ketish', 'Olib ketish')], default='yetkazib_berish', max_length=20, verbose_name='Yetkazish turi')),
                ('delivery_time_slot', models.CharField(blank=True, help_text='Masalan: 14:00–16:00', max_length=100, verbose_name='Yetkazish vaqti')),
                ('payment_method', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('naqd', 'Naqd pul')], default='naqd', max_length=10, verbose_name="To'lov usuli")),
                ('payment_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('failed', 'Xatolik')], default='pending', max_length=10, verbose_name="To'lov holati")),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Mahsulotlar summasi')),
                ('delivery_fee', models.PositiveIntegerField(default=0, verbose_name='Yetkazish narxi')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Jami summa')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address', verbose_name='Manzil')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(help_text='Saved at order time to preserve history', max_length=250, verbose_name='Mahsulot nomi (snapshot)')),
                ('variant_weight_snapshot', models.CharField(blank=True, max_length=50, verbose_name="Variant og'irligi (snapshot)")),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Miqdor')),
                ('price_at_order', models.PositiveIntegerField(verbose_name='Narx (buyurtma vaqtida)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
    ]
