# Generated by Django 5.2.16 on 2026-07-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kodi')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Chegirma foizi')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='Chegirma summasi')),
                ('valid_until', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('usage_limit', models.PositiveIntegerField(default=100, verbose_name='Ishlatilish limiti')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan soni')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='Minimal buyurtma summasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Promo-kod',
                'verbose_name_plural': 'Promo-kodlar',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Chegirma summasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='Promo-kod'),
        ),
    ]
