# Generated by Django 5.2.16 on 2026-07-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(verbose_name='Rejalashtirilgan vaqt')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Yuborildimi')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baholash (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Fikr-mulohaza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_request', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': "Fikr-mulohaza so'rovi",
                'verbose_name_plural': "Fikr-mulohaza so'rovlari",
            },
        ),
    ]
