# Generated by Django 5.2.16 on 2026-07-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_feedbackrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name="Vaqt oralig'i (matn)")),
                ('date', models.DateField(verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('max_orders', models.PositiveSmallIntegerField(default=20, verbose_name='Maksimal buyurtmalar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Yetkazib berish vaqti',
                'verbose_name_plural': 'Yetkazib berish vaqtlari',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE orders_order ALTER COLUMN delivery_time_slot DROP NOT NULL; UPDATE orders_order SET delivery_time_slot = NULL;",
            reverse_sql=""
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliverytimeslot', verbose_name='Yetkazish vaqti'),
        ),
    ]
