# Generated by Django 5.2.16 on 2026-07-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productbundle_product_related_products_bundleitem'),
        ('orders', '0005_deliverytimeslot_alter_order_delivery_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productbundle', verbose_name="To'plam"),
        ),
    ]
