# Generated by Django 5.2.16 on 2026-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_bundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Kompaniya / Tashkilot nomi')),
                ('contact_person', models.CharField(max_length=150, verbose_name='Aloqachi shaxs')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('estimated_quantity', models.PositiveIntegerField(default=1, verbose_name='Taxminiy soni')),
                ('comment', models.TextField(blank=True, verbose_name="Izoh / Qo'shimcha ma'lumotlar")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': "Korporativ so'rov",
                'verbose_name_plural': "Korporativ so'rovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
