# Generated by Django 5.1.15 on 2026-07-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_corporateinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Kapitalbank', max_length=100, verbose_name='Bank nomi')),
                ('card_number', models.CharField(max_length=30, verbose_name='Karta raqami')),
                ('card_holder', models.CharField(max_length=100, verbose_name='Karta egasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bank kartasi',
                'verbose_name_plural': 'Bank kartalari',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/', verbose_name="To'lov cheki (rasm)"),
        ),
    ]
