# Generated by Django 5.1.15 on 2026-07-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_bankcard_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashback_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Ishlangan keshbek'),
        ),
        migrations.AddField(
            model_name='order',
            name='cashback_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan keshbek'),
        ),
    ]
