# Generated by Django 5.1.15 on 2026-07-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_telegramuser_cashback_balance'),
        ('orders', '0009_order_cashback_earned_order_cashback_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='used_by_users',
            field=models.ManyToManyField(blank=True, related_name='used_promocodes', to='accounts.telegramuser', verbose_name='Ishlatgan foydalanuvchilar'),
        ),
    ]
