# Generated by Django 5.2.16 on 2026-07-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_banner_product_is_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='weight_label',
            new_name='label',
        ),
    ]
