# Generated by Django 5.2.16 on 2026-07-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_weight_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['order', 'price'], 'verbose_name': 'Mahsulot varianti', 'verbose_name_plural': 'Mahsulot variantlari'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mahsulot ochilganda avtomatik tanlanadi', verbose_name='Asosiy variant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('weight', "Og'irlik"), ('piece', 'Dona'), ('flavor', "Ta'm"), ('volume', 'Hajm')], default='weight', max_length=20, verbose_name='Variant turi'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='label',
            field=models.CharField(help_text="Masalan: 100g, 25 dona, Olma ta'mli", max_length=100, verbose_name='Variant nomi'),
        ),
    ]
