# Generated by Django 5.2.16 on 2026-07-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('sht', 'SHT'), ('gr', 'GR'), ('kg', 'KG')], default='sht', max_length=20, verbose_name='Variant turi'),
        ),
    ]
