# Generated by Django 5.2.16 on 2026-07-10 15:52

from django.db import migrations


def migrate_types(apps, schema_editor):
    ProductVariant = apps.get_model('catalog', 'ProductVariant')
    
    # Mapping old values to new values
    # old types: 'weight', 'piece', 'flavor', 'volume'
    for variant in ProductVariant.objects.all():
        if variant.variant_type == 'piece':
            variant.variant_type = 'sht'
        elif variant.variant_type == 'weight':
            variant.variant_type = 'kg'
        elif variant.variant_type == 'volume':
            variant.variant_type = 'l' # even though we don't have L, fallback to sht
            variant.variant_type = 'sht'
        elif variant.variant_type == 'flavor':
            variant.variant_type = 'sht'
        
        if variant.variant_type not in ['sht', 'gr', 'kg']:
            variant.variant_type = 'sht'
            
        variant.save()

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productvariant_variant_type'),
    ]

    operations = [
        migrations.RunPython(migrate_types, reverse_migrate),
    ]
