# Generated by Django 5.2.16 on 2026-07-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0006_migrate_variant_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sevimli mahsulot',
                'verbose_name_plural': 'Sevimli mahsulotlar',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
