# Generated by Django 5.2.16 on 2026-07-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_favoriteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(default='Batafsil', max_length=50, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='banner',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Havola (URL)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='last_low_stock_notified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi ogohlantirish vaqti'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kichik matn'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
    ]
