# Generated by Django 5.2.16 on 2026-07-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_banner_button_text_banner_ends_at_banner_link_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Chegirma (%)')),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant', verbose_name='Mahsulot varianti')),
            ],
            options={
                'verbose_name': 'Kunlik taklif',
                'verbose_name_plural': 'Kunlik takliflar',
                'ordering': ['-date'],
            },
        ),
    ]
