# Generated by Django 5.2.16 on 2026-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Shtrix kod'),
        ),
    ]
