# Generated by Django 5.2.16 on 2026-07-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productvariant_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="To'plam nomi")),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('image', models.ImageField(upload_to='bundles/', verbose_name="To'plam rasmi")),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Chegirma foizi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "To'plam (Combo)",
                'verbose_name_plural': "To'plamlar (Combo)",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='catalog.product', verbose_name="O'xshash mahsulotlar"),
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Soni')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='catalog.productvariant', verbose_name='Variant')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.productbundle', verbose_name="To'plam")),
            ],
            options={
                'verbose_name': "To'plam elementi",
                'verbose_name_plural': "To'plam elementlari",
            },
        ),
    ]
