# Generated by Django 5.1.15 on 2026-07-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_dailydeal_starts_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydeal',
            options={'ordering': ['-id'], 'verbose_name': 'Kunlik taklif', 'verbose_name_plural': 'Kunlik takliflar'},
        ),
        migrations.RemoveField(
            model_name='dailydeal',
            name='date',
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=15000, verbose_name='Yetkazib berish narxi (UZS)'),
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/', verbose_name='Taklif rasmi'),
        ),
    ]
