# Generated by Django 5.2.16 on 2026-07-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kuryer',
                'verbose_name_plural': 'Kuryerlar',
            },
        ),
    ]
