# Generated by Django 5.2.16 on 2026-07-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik'),
        ),
    ]
