# Generated by Django 5.1.15 on 2026-07-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='cashback_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Keshbek balansi (UZS)'),
        ),
    ]
