# Generated by Django 5.2.16 on 2026-07-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.BigIntegerField(db_index=True, verbose_name='Click trans ID')),
                ('click_paydoc_id', models.BigIntegerField(blank=True, null=True, verbose_name='Click paydoc ID')),
                ('merchant_trans_id', models.CharField(max_length=255, verbose_name='Merchant trans ID (order_id)')),
                ('status', models.SmallIntegerField(choices=[(0, 'Kutilmoqda'), (1, 'Tasdiqlandi'), (-1, 'Bekor qilindi'), (-2, "Allaqachon to'langan")], default=0, verbose_name='Holat')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('sign_time', models.CharField(max_length=20, verbose_name='Sign time')),
                ('error', models.SmallIntegerField(default=0, verbose_name='Xato kodi')),
                ('error_note', models.CharField(blank=True, max_length=255, verbose_name='Xato matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_transactions', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Click tranzaksiya',
                'verbose_name_plural': 'Click tranzaksiyalar',
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_transaction_id', models.CharField(max_length=255, unique=True, verbose_name='Payme transaction ID')),
                ('payme_time', models.BigIntegerField(help_text='Transaction create time from Payme (Unix ms)')),
                ('state', models.SmallIntegerField(choices=[(1, 'Yaratildi'), (2, 'Amalga oshirildi'), (-1, "Bekor qilindi (to'lovdan oldin)"), (-2, "Bekor qilindi (to'lovdan keyin)")], default=1, verbose_name='Holat')),
                ('amount', models.BigIntegerField(verbose_name='Summa (tiyin)')),
                ('reason', models.SmallIntegerField(blank=True, choices=[(1, 'Qabul qiluvchi topilmadi'), (2, 'Bajarish muammosi'), (3, 'Xatolik'), (4, 'Vaqt tugadi'), (5, 'Qaytarildi'), (10, "Noma'lum")], null=True, verbose_name='Bekor qilish sababi')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('perform_time', models.DateTimeField(blank=True, null=True, verbose_name='Amalga oshirilgan vaqt')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_transactions', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Payme tranzaksiya',
                'verbose_name_plural': 'Payme tranzaksiyalar',
            },
        ),
    ]
